ERROR 2025-10-24 11:02:36,258 basehttp 69592 93380 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:02:36,261 basehttp 69592 74704 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:05:47,452 basehttp 69592 50964 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:05:47,455 basehttp 69592 84280 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:06:25,382 basehttp 69592 88280 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:06:25,386 basehttp 69592 94244 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:06:40,520 basehttp 69592 95164 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:06:40,779 basehttp 69592 95012 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:06:40,828 basehttp 69592 95728 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:06:41,085 basehttp 69592 60016 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:08:11,788 basehttp 69592 96836 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:08:12,035 basehttp 69592 86160 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:08:12,099 basehttp 69592 78396 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:08:12,347 basehttp 69592 94084 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:09:45,956 basehttp 69592 62808 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:09:45,957 basehttp 69592 95204 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:50,748 basehttp 64464 83036 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:50,749 basehttp 64464 31952 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:50,754 basehttp 64464 79220 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:50,756 basehttp 64464 97044 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:52,153 basehttp 64464 93064 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:52,155 basehttp 64464 81876 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:52,158 basehttp 64464 79112 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:52,159 basehttp 64464 91300 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:58,573 basehttp 64464 95560 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:12:58,576 basehttp 64464 95524 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-24 11:19:01,620 basehttp 64464 95440 "GET / HTTP/1.1" 400 143
WARNING 2025-10-24 11:19:01,999 basehttp 64464 94192 "GET /favicon.ico HTTP/1.1" 400 143
ERROR 2025-10-24 11:23:09,900 basehttp 79100 94320 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:23:09,903 basehttp 79100 97220 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:22,196 basehttp 79100 96376 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:22,200 basehttp 79100 89180 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:34,002 basehttp 79100 70788 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:34,006 basehttp 79100 94428 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:43,316 basehttp 79100 86536 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:43,319 basehttp 79100 90236 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:56,071 basehttp 68876 36032 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:56,072 basehttp 68876 76572 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:56,074 basehttp 68876 97140 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:24:56,077 basehttp 68876 92340 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:25:00,161 basehttp 68876 79764 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:25:00,163 basehttp 68876 84516 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:25:15,182 basehttp 68876 92780 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:25:15,187 basehttp 68876 96912 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:25:48,855 basehttp 68876 91364 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:25:48,861 basehttp 68876 87560 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:26:41,222 basehttp 91916 97176 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:26:41,224 basehttp 91916 96412 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:27:19,022 basehttp 91916 91480 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:27:19,024 basehttp 91916 88140 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-24 11:27:24,305 log 91916 91404 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:24,306 basehttp 91916 91404 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:24,530 log 91916 91404 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:24,532 basehttp 91916 91404 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:24,585 log 91916 91404 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:24,585 basehttp 91916 91404 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:24,940 log 91916 91404 Not Found: /static/favicon.ico
WARNING 2025-10-24 11:27:24,941 basehttp 91916 91404 "GET /static/favicon.ico HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:29,631 log 91916 91404 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:27:29,633 basehttp 91916 91404 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:29,985 log 91916 87488 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:27:29,987 basehttp 91916 87488 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:30,043 log 91916 90628 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:30,045 basehttp 91916 90628 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:30,105 log 91916 94092 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:30,105 basehttp 91916 94092 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:32,580 log 91916 87488 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:27:32,580 basehttp 91916 87488 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:32,634 log 91916 91404 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:32,636 basehttp 91916 91404 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:32,696 log 91916 94092 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:32,697 basehttp 91916 94092 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:32,750 log 91916 90628 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:27:32,751 basehttp 91916 90628 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:35,795 log 91916 87488 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:35,796 basehttp 91916 87488 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:35,854 log 91916 91404 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:27:35,855 basehttp 91916 91404 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:35,916 log 91916 94092 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:27:35,917 basehttp 91916 94092 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:35,971 log 91916 90628 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:35,972 basehttp 91916 90628 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:40,465 log 91916 87488 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:40,466 basehttp 91916 87488 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:40,521 log 91916 90628 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:40,522 basehttp 91916 90628 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:40,582 log 91916 91404 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:27:40,583 basehttp 91916 91404 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:40,643 log 91916 94092 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:27:40,646 basehttp 91916 94092 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:43,238 log 91916 87488 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:43,239 basehttp 91916 87488 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:43,294 log 91916 91404 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:27:43,295 basehttp 91916 91404 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:43,349 log 91916 90628 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:27:43,350 basehttp 91916 90628 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:43,410 log 91916 94092 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:43,411 basehttp 91916 94092 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:51,108 log 91916 90628 Not Found: /static/js/base.js
WARNING 2025-10-24 11:27:51,109 basehttp 91916 90628 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:27:51,172 log 91916 94092 Not Found: /static/css/base.css
WARNING 2025-10-24 11:27:51,174 basehttp 91916 94092 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:56,198 log 91916 91404 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:28:56,198 basehttp 91916 91404 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:56,254 log 91916 87488 Not Found: /static/js/base.js
WARNING 2025-10-24 11:28:56,255 basehttp 91916 87488 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:56,313 log 91916 94092 Not Found: /static/css/base.css
WARNING 2025-10-24 11:28:56,314 basehttp 91916 94092 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:56,366 log 91916 90628 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:28:56,366 basehttp 91916 90628 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:58,217 log 91916 87488 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:28:58,218 basehttp 91916 87488 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:58,271 log 91916 90628 Not Found: /static/css/base.css
WARNING 2025-10-24 11:28:58,272 basehttp 91916 90628 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:58,334 log 91916 94092 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:28:58,334 basehttp 91916 94092 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:28:58,388 log 91916 91404 Not Found: /static/js/base.js
WARNING 2025-10-24 11:28:58,389 basehttp 91916 91404 "GET /static/js/base.js HTTP/1.1" 404 179
ERROR 2025-10-24 11:29:04,053 basehttp 91916 43324 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 11:29:04,055 basehttp 91916 95472 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-24 11:29:10,815 log 91916 44312 Not Found: /static/css/base.css
WARNING 2025-10-24 11:29:10,815 basehttp 91916 44312 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:11,006 log 91916 44312 Not Found: /static/js/base.js
WARNING 2025-10-24 11:29:11,007 basehttp 91916 44312 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:11,039 log 91916 44312 Not Found: /static/css/base.css
WARNING 2025-10-24 11:29:11,040 basehttp 91916 44312 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:15,524 log 91916 44312 Not Found: /static/css/base.css
WARNING 2025-10-24 11:29:15,526 log 91916 95332 Not Found: /static/js/base.js
WARNING 2025-10-24 11:29:15,527 basehttp 91916 44312 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:15,527 basehttp 91916 95332 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:16,714 log 91916 44312 Not Found: /static/css/base.css
WARNING 2025-10-24 11:29:16,714 basehttp 91916 44312 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:16,722 log 91916 90416 Not Found: /static/js/base.js
WARNING 2025-10-24 11:29:16,723 log 91916 96748 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:29:16,725 log 91916 44312 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:29:16,726 basehttp 91916 90416 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:16,726 basehttp 91916 96748 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:16,727 basehttp 91916 44312 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:17,051 log 91916 44312 Not Found: /static/css/base.css
WARNING 2025-10-24 11:29:17,053 log 91916 96748 Not Found: /static/css/dichvudiennuoc_quanlykhachthue.css
WARNING 2025-10-24 11:29:17,053 log 91916 90416 Not Found: /static/js/dichvudiennuoc_quanlykhachthue.js
WARNING 2025-10-24 11:29:17,053 basehttp 91916 44312 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:17,055 log 91916 96616 Not Found: /static/js/base.js
WARNING 2025-10-24 11:29:17,056 basehttp 91916 96748 "GET /static/css/dichvudiennuoc_quanlykhachthue.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:17,057 basehttp 91916 90416 "GET /static/js/dichvudiennuoc_quanlykhachthue.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:29:17,058 basehttp 91916 96616 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:08,253 log 91916 87032 Not Found: /static/css/base.css
WARNING 2025-10-24 11:30:08,254 basehttp 91916 87032 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:08,561 log 91916 87032 Not Found: /static/js/base.js
WARNING 2025-10-24 11:30:08,562 log 91916 67972 Not Found: /static/css/base.css
WARNING 2025-10-24 11:30:08,562 basehttp 91916 87032 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:08,564 basehttp 91916 67972 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:12,765 log 91916 87032 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:30:12,766 basehttp 91916 87032 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:12,827 log 91916 6680 Not Found: /static/js/base.js
WARNING 2025-10-24 11:30:12,828 basehttp 91916 6680 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:13,733 log 91916 67972 Not Found: /static/css/base.css
WARNING 2025-10-24 11:30:13,734 basehttp 91916 67972 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:13,813 log 91916 96608 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:30:13,814 basehttp 91916 96608 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:17,623 log 91916 67972 Not Found: /static/css/dichvudiennuoc_quanlykhachthue.css
WARNING 2025-10-24 11:30:17,624 basehttp 91916 67972 "GET /static/css/dichvudiennuoc_quanlykhachthue.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:17,690 log 91916 96608 Not Found: /static/css/base.css
WARNING 2025-10-24 11:30:17,691 basehttp 91916 96608 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:17,761 log 91916 6680 Not Found: /static/js/dichvudiennuoc_quanlykhachthue.js
WARNING 2025-10-24 11:30:17,763 basehttp 91916 6680 "GET /static/js/dichvudiennuoc_quanlykhachthue.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:17,826 log 91916 87032 Not Found: /static/js/base.js
WARNING 2025-10-24 11:30:17,827 basehttp 91916 87032 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:26,950 log 91916 96608 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:30:26,950 basehttp 91916 96608 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:27,003 log 91916 67972 Not Found: /static/js/base.js
WARNING 2025-10-24 11:30:27,004 basehttp 91916 67972 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:27,060 log 91916 6680 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:30:27,061 basehttp 91916 6680 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:27,115 log 91916 87032 Not Found: /static/css/base.css
WARNING 2025-10-24 11:30:27,116 basehttp 91916 87032 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:38,195 log 91916 67972 Not Found: /static/js/dichvudiennuoc_baocaodoanhthu.js
WARNING 2025-10-24 11:30:38,195 basehttp 91916 67972 "GET /static/js/dichvudiennuoc_baocaodoanhthu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:38,247 log 91916 96608 Not Found: /static/js/base.js
WARNING 2025-10-24 11:30:38,248 basehttp 91916 96608 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:38,304 log 91916 6680 Not Found: /static/css/dichvudiennuoc_baocaodoanhthu.css
WARNING 2025-10-24 11:30:38,304 basehttp 91916 6680 "GET /static/css/dichvudiennuoc_baocaodoanhthu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:30:38,359 log 91916 87032 Not Found: /static/css/base.css
WARNING 2025-10-24 11:30:38,360 basehttp 91916 87032 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:20,737 log 95588 95372 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:20,738 basehttp 95588 95372 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:21,052 log 95588 85248 Not Found: /static/css/dichvudiennuoc_baocaodoanhthu.css
WARNING 2025-10-24 11:34:21,053 basehttp 95588 85248 "GET /static/css/dichvudiennuoc_baocaodoanhthu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:21,130 log 95588 89864 Not Found: /static/js/dichvudiennuoc_baocaodoanhthu.js
WARNING 2025-10-24 11:34:21,132 basehttp 95588 89864 "GET /static/js/dichvudiennuoc_baocaodoanhthu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:21,306 log 95588 62808 Not Found: /static/js/base.js
WARNING 2025-10-24 11:34:21,308 basehttp 95588 62808 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:24,822 log 95588 89864 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:34:24,825 basehttp 95588 89864 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:24,878 log 95588 85248 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:34:24,881 basehttp 95588 85248 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:24,937 log 95588 95372 Not Found: /static/js/base.js
WARNING 2025-10-24 11:34:24,942 basehttp 95588 95372 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:24,993 log 95588 62808 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:24,996 basehttp 95588 62808 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:25,989 log 95588 62808 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:25,992 basehttp 95588 62808 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:26,051 log 95588 95372 Not Found: /static/css/dichvudiennuoc_quanlykhachthue.css
WARNING 2025-10-24 11:34:26,052 basehttp 95588 95372 "GET /static/css/dichvudiennuoc_quanlykhachthue.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:26,106 log 95588 85248 Not Found: /static/js/base.js
WARNING 2025-10-24 11:34:26,108 basehttp 95588 85248 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:26,165 log 95588 89864 Not Found: /static/js/dichvudiennuoc_quanlykhachthue.js
WARNING 2025-10-24 11:34:26,166 basehttp 95588 89864 "GET /static/js/dichvudiennuoc_quanlykhachthue.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:27,350 log 95588 89864 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:27,351 basehttp 95588 89864 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:27,405 log 95588 85248 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:34:27,407 basehttp 95588 85248 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:27,460 log 95588 62808 Not Found: /static/js/base.js
WARNING 2025-10-24 11:34:27,464 basehttp 95588 62808 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:27,520 log 95588 95372 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:34:27,522 basehttp 95588 95372 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:34,968 log 95588 85904 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:34,970 basehttp 95588 85904 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:35,233 log 95588 85904 Not Found: /static/js/base.js
WARNING 2025-10-24 11:34:35,235 basehttp 95588 85904 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:35,275 log 95588 85904 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:35,276 basehttp 95588 85904 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:42,912 log 95588 96336 Not Found: /static/css/base.css
WARNING 2025-10-24 11:34:42,913 log 95588 90300 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:34:42,916 log 95588 81856 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:34:42,916 log 95588 90356 Not Found: /static/js/base.js
WARNING 2025-10-24 11:34:42,917 basehttp 95588 96336 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:42,917 basehttp 95588 90300 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:42,918 basehttp 95588 81856 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:34:42,918 basehttp 95588 90356 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:17,290 log 59748 94308 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:17,291 basehttp 59748 94308 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:17,297 log 59748 96552 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:39:17,297 log 59748 80928 Not Found: /static/js/dichvudiennuoc_quanlyloaidichvu.js
WARNING 2025-10-24 11:39:17,299 basehttp 59748 96552 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:17,299 basehttp 59748 80928 "GET /static/js/dichvudiennuoc_quanlyloaidichvu.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:17,497 log 59748 80928 Not Found: /static/js/base.js
WARNING 2025-10-24 11:39:17,500 basehttp 59748 80928 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:17,500 log 59748 96552 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:17,502 log 59748 94308 Not Found: /static/css/dichvudiennuoc_quanlyloaidichvu.css
WARNING 2025-10-24 11:39:17,503 basehttp 59748 96552 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:17,504 basehttp 59748 94308 "GET /static/css/dichvudiennuoc_quanlyloaidichvu.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:19,919 log 59748 94308 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:19,921 basehttp 59748 94308 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:20,250 log 59748 93852 Not Found: /static/js/base.js
WARNING 2025-10-24 11:39:20,251 basehttp 59748 93852 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:20,308 log 59748 96552 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:39:20,309 basehttp 59748 96552 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:20,364 log 59748 80928 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:39:20,366 basehttp 59748 80928 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:22,099 log 59748 93852 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 11:39:22,101 basehttp 59748 93852 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:22,157 log 59748 80928 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:22,159 basehttp 59748 80928 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:22,216 log 59748 96552 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 11:39:22,218 basehttp 59748 96552 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:22,274 log 59748 94308 Not Found: /static/js/base.js
WARNING 2025-10-24 11:39:26,995 log 59748 5804 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:26,997 basehttp 59748 5804 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:27,275 log 59748 5804 Not Found: /static/js/base.js
WARNING 2025-10-24 11:39:27,276 basehttp 59748 5804 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:27,321 log 59748 5804 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:27,322 basehttp 59748 5804 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:29,472 log 59748 5804 Not Found: /static/css/base.css
WARNING 2025-10-24 11:39:29,473 basehttp 59748 5804 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:29,479 log 59748 88800 Not Found: /static/css/dichvudiennuoc_quanlykhachthue.css
WARNING 2025-10-24 11:39:29,481 log 59748 71544 Not Found: /static/js/dichvudiennuoc_quanlykhachthue.js
WARNING 2025-10-24 11:39:29,482 log 59748 87756 Not Found: /static/js/base.js
WARNING 2025-10-24 11:39:29,483 basehttp 59748 88800 "GET /static/css/dichvudiennuoc_quanlykhachthue.css HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:29,484 basehttp 59748 71544 "GET /static/js/dichvudiennuoc_quanlykhachthue.js HTTP/1.1" 404 179
WARNING 2025-10-24 11:39:29,485 basehttp 59748 87756 "GET /static/js/base.js HTTP/1.1" 404 179
ERROR 2025-10-24 15:00:14,795 basehttp 97796 99484 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:00:14,798 basehttp 97796 91364 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-24 15:00:20,828 log 97796 87072 Not Found: /static/css/base.css
WARNING 2025-10-24 15:00:20,830 basehttp 97796 87072 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:00:21,098 log 97796 87072 Not Found: /static/js/base.js
WARNING 2025-10-24 15:00:21,099 basehttp 97796 87072 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:00:21,154 log 97796 87072 Not Found: /static/css/base.css
WARNING 2025-10-24 15:00:21,155 basehttp 97796 87072 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:00:35,294 log 97796 87072 Not Found: /static/css/base.css
WARNING 2025-10-24 15:00:35,296 log 97796 60200 Not Found: /static/js/base.js
WARNING 2025-10-24 15:00:35,297 basehttp 97796 87072 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:00:35,298 basehttp 97796 60200 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:30,942 log 89440 81212 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:30,942 basehttp 89440 81212 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:30,945 log 89440 97668 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:30,946 basehttp 89440 97668 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:33,239 log 89440 97668 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:33,240 log 89440 81212 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:33,242 basehttp 89440 97668 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:33,242 basehttp 89440 81212 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:34,673 log 89440 81212 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:34,674 basehttp 89440 81212 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:34,893 log 89440 81212 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:34,895 log 89440 97668 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:34,896 basehttp 89440 81212 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:34,897 basehttp 89440 97668 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:38,968 log 89440 97668 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:38,970 basehttp 89440 97668 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:39,315 log 89440 81212 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 15:03:39,317 basehttp 89440 81212 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:39,368 log 89440 90648 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:39,370 basehttp 89440 90648 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:39,432 log 89440 94324 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 15:03:39,436 basehttp 89440 94324 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:40,025 log 89440 81212 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:40,026 basehttp 89440 81212 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:40,079 log 89440 90648 Not Found: /static/js/dichvudiennuoc_quanlykhachthue.js
WARNING 2025-10-24 15:03:40,082 basehttp 89440 90648 "GET /static/js/dichvudiennuoc_quanlykhachthue.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:40,139 log 89440 97668 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:40,141 basehttp 89440 97668 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:40,200 log 89440 94324 Not Found: /static/css/dichvudiennuoc_quanlykhachthue.css
WARNING 2025-10-24 15:03:40,201 basehttp 89440 94324 "GET /static/css/dichvudiennuoc_quanlykhachthue.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:41,797 log 89440 90648 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 15:03:41,799 basehttp 89440 90648 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:41,855 log 89440 81212 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:41,857 basehttp 89440 81212 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:41,919 log 89440 94324 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:41,922 basehttp 89440 94324 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:41,978 log 89440 97668 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 15:03:41,980 basehttp 89440 97668 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:44,656 log 89440 81212 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 15:03:44,656 basehttp 89440 81212 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:44,715 log 89440 97668 Not Found: /static/css/base.css
WARNING 2025-10-24 15:03:44,719 basehttp 89440 97668 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:44,776 log 89440 94324 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 15:03:44,777 basehttp 89440 94324 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:03:44,829 log 89440 90648 Not Found: /static/js/base.js
WARNING 2025-10-24 15:03:44,831 basehttp 89440 90648 "GET /static/js/base.js HTTP/1.1" 404 179
ERROR 2025-10-24 15:04:06,027 basehttp 89440 96424 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:04:06,030 basehttp 89440 99416 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-24 15:06:46,700 log 94128 93096 Not Found: /static/css/base.css
WARNING 2025-10-24 15:06:46,701 basehttp 94128 93096 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:06:47,096 log 94128 96736 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 15:06:47,097 basehttp 94128 96736 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:06:47,156 log 94128 88044 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 15:06:47,158 basehttp 94128 88044 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:06:47,243 log 94128 101292 Not Found: /static/js/base.js
WARNING 2025-10-24 15:06:47,244 basehttp 94128 101292 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:49,106 log 94128 98296 Not Found: /static/css/base.css
WARNING 2025-10-24 15:07:49,107 basehttp 94128 98296 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:49,333 log 94128 98296 Not Found: /static/js/base.js
WARNING 2025-10-24 15:07:49,334 basehttp 94128 98296 "GET /static/js/base.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:49,374 log 94128 98296 Not Found: /static/css/base.css
WARNING 2025-10-24 15:07:49,374 basehttp 94128 98296 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:49,736 log 94128 98296 Not Found: /static/favicon.ico
WARNING 2025-10-24 15:07:49,738 basehttp 94128 98296 "GET /static/favicon.ico HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:55,341 log 94128 98296 Not Found: /static/css/base.css
WARNING 2025-10-24 15:07:55,342 basehttp 94128 98296 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:55,567 log 94128 98296 Not Found: /static/js/dichvudiennuoc_danhsachthongbao.js
WARNING 2025-10-24 15:07:55,569 basehttp 94128 98296 "GET /static/js/dichvudiennuoc_danhsachthongbao.js HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:55,681 log 94128 95740 Not Found: /static/css/dichvudiennuoc_danhsachthongbao.css
WARNING 2025-10-24 15:07:55,682 basehttp 94128 95740 "GET /static/css/dichvudiennuoc_danhsachthongbao.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:56,023 log 94128 99184 Not Found: /static/js/base.js
WARNING 2025-10-24 15:07:56,424 log 94128 95740 Not Found: /static/css/base.css
WARNING 2025-10-24 15:07:56,424 basehttp 94128 95740 "GET /static/css/base.css HTTP/1.1" 404 179
WARNING 2025-10-24 15:07:56,479 log 94128 98296 Not Found: /static/js/base.js
WARNING 2025-10-24 15:07:56,482 basehttp 94128 98296 "GET /static/js/base.js HTTP/1.1" 404 179
ERROR 2025-10-24 15:10:59,569 basehttp 95740 97284 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:10:59,824 basehttp 95740 58248 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:10:59,882 basehttp 95740 94460 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:00,131 basehttp 95740 100416 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:18,506 basehttp 76288 99360 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:18,508 basehttp 76288 87640 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:18,761 basehttp 76288 83564 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:18,817 basehttp 76288 99504 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:18,817 basehttp 76288 96860 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:11:19,065 basehttp 76288 89244 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:16:43,719 basehttp 76288 88528 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:16:43,967 basehttp 76288 83700 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:16:44,030 basehttp 76288 101072 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 15:16:44,283 basehttp 76288 86420 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-24 15:20:39,446 basehttp 102396 94740 "POST /dichvudiennuoc/api/quanlykhachthue/update-or-create/ HTTP/1.1" 403 2549
WARNING 2025-10-24 15:20:49,514 log 102396 94740 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-24 15:20:49,515 basehttp 102396 94740 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2898
WARNING 2025-10-24 15:21:00,836 basehttp 102396 94740 "POST /dichvudiennuoc/api/quanlykhachthue/update-or-create/ HTTP/1.1" 403 2549
WARNING 2025-10-24 15:35:23,898 basehttp 100780 79620 "POST /dichvudiennuoc/api/loaidichvu/update-or-create/ HTTP/1.1" 403 2855
WARNING 2025-10-24 15:35:28,603 log 100780 79620 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-24 15:35:28,604 basehttp 100780 79620 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2898
WARNING 2025-10-24 15:35:35,376 basehttp 100780 79620 "POST /dichvudiennuoc/api/loaidichvu/update-or-create/ HTTP/1.1" 403 2855
WARNING 2025-10-24 15:53:45,661 log 98244 84244 Bad Request: /dichvudiennuoc/api/dichvu/update-or-create/
WARNING 2025-10-24 15:53:45,663 basehttp 98244 84244 "POST /dichvudiennuoc/api/dichvu/update-or-create/ HTTP/1.1" 400 212
WARNING 2025-10-24 15:53:48,602 log 98244 84244 Bad Request: /dichvudiennuoc/api/dichvu/update-or-create/
WARNING 2025-10-24 15:53:48,606 basehttp 98244 84244 "POST /dichvudiennuoc/api/dichvu/update-or-create/ HTTP/1.1" 400 212
WARNING 2025-10-24 15:53:50,799 log 98244 84244 Bad Request: /dichvudiennuoc/api/dichvu/update-or-create/
WARNING 2025-10-24 15:53:50,802 basehttp 98244 84244 "POST /dichvudiennuoc/api/dichvu/update-or-create/ HTTP/1.1" 400 212
WARNING 2025-10-24 15:53:52,964 log 98244 84244 Bad Request: /dichvudiennuoc/api/dichvu/update-or-create/
WARNING 2025-10-24 15:53:52,966 basehttp 98244 84244 "POST /dichvudiennuoc/api/dichvu/update-or-create/ HTTP/1.1" 400 212
WARNING 2025-10-24 15:55:31,754 basehttp 98244 91288 "POST /dichvudiennuoc/api/quanlykhachthue/update-or-create/ HTTP/1.1" 403 2549
WARNING 2025-10-24 16:00:21,054 basehttp 97124 94988 "POST /dichvudiennuoc/api/quanlykhachthue/update-or-create/ HTTP/1.1" 403 2549
WARNING 2025-10-24 16:02:04,786 log 97124 99644 Bad Request: /dichvudiennuoc/api/quanlykhachthue/update-or-create/
WARNING 2025-10-24 16:02:04,788 basehttp 97124 99644 "POST /dichvudiennuoc/api/quanlykhachthue/update-or-create/ HTTP/1.1" 400 146
ERROR 2025-10-24 16:39:55,300 basehttp 97124 98816 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-24 16:39:55,306 basehttp 97124 98424 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-27 11:52:39,525 log 9196 6364 Not Found: /favicon.ico
WARNING 2025-10-27 11:52:39,531 basehttp 9196 6364 "GET /favicon.ico HTTP/1.1" 404 2787
WARNING 2025-10-27 11:53:34,657 basehttp 9196 1660 "POST /dichvudiennuoc/api/tao-moi-thong-bao/ HTTP/1.1" 403 2538
WARNING 2025-10-27 15:26:42,562 log 7188 10168 Not Found: /favicon.ico
WARNING 2025-10-27 15:26:42,564 basehttp 7188 10168 "GET /favicon.ico HTTP/1.1" 404 2787
WARNING 2025-10-27 15:30:53,844 log 7188 17228 Not Found: /favicon.ico
WARNING 2025-10-27 15:30:53,846 basehttp 7188 17228 "GET /favicon.ico HTTP/1.1" 404 2787
WARNING 2025-10-28 15:09:52,535 basehttp 22600 2520 "POST /dichvudiennuoc/api/tao-moi-thong-bao/ HTTP/1.1" 403 2538
WARNING 2025-10-28 15:29:52,544 basehttp 9836 9796 "DELETE /dichvudiennuoc/api/xoa-thong-bao/388/ HTTP/1.1" 403 2538
WARNING 2025-10-28 15:36:47,750 basehttp 9836 20396 "DELETE /dichvudiennuoc/api/xoa-thong-bao/388/ HTTP/1.1" 403 2538
WARNING 2025-10-28 15:37:51,475 basehttp 9836 132 "DELETE /dichvudiennuoc/api/xoa-thong-bao/388/ HTTP/1.1" 403 2538
WARNING 2025-10-28 15:38:26,620 basehttp 9836 20396 "POST /dichvudiennuoc/api/tao-moi-thong-bao/ HTTP/1.1" 403 2538
ERROR 2025-10-28 16:01:43,755 basehttp 22968 7728 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:01:43,756 basehttp 22968 19224 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:01:46,978 basehttp 22968 10100 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:01:46,980 basehttp 22968 11144 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:01:47,510 basehttp 22968 16028 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:01:47,512 basehttp 22968 7472 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:08:56,548 basehttp 22968 9860 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:08:56,550 basehttp 22968 16888 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:08:58,017 basehttp 22968 19824 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:08:58,020 basehttp 22968 7860 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:08:59,088 basehttp 22968 18664 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:08:59,089 basehttp 22968 14284 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:00,020 basehttp 22968 21400 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:00,022 basehttp 22968 2964 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:00,538 basehttp 22968 4616 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:00,541 basehttp 22968 2676 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:11,685 basehttp 23108 12260 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:11,686 basehttp 23108 17320 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:12,330 basehttp 23108 18464 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-10-28 16:09:12,332 basehttp 23108 3428 You're accessing the development server over HTTPS, but it only supports HTTP.
WARNING 2025-10-29 11:25:52,001 basehttp 148896 134928 "GET / HTTP/1.1" 400 87781
WARNING 2025-10-29 11:26:14,621 log 148896 134928 Not Found: /dashboard
WARNING 2025-10-29 11:26:14,622 basehttp 148896 134928 "GET /dashboard HTTP/1.1" 404 2838
WARNING 2025-10-29 11:26:20,821 log 148896 134928 Not Found: /dichvudiennuoc
WARNING 2025-10-29 11:26:20,822 basehttp 148896 134928 "GET /dichvudiennuoc HTTP/1.1" 404 2853
WARNING 2025-10-29 11:27:02,666 basehttp 148896 147212 "GET / HTTP/1.1" 400 87632
ERROR 2025-10-29 11:35:02,418 log 118344 151524 Internal Server Error: /
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'dashboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 259, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 249, in get_redirect_url
    url = reverse(self.pattern_name, args=args, kwargs=kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'dashboard' is not a registered namespace
ERROR 2025-10-29 11:35:02,420 basehttp 118344 151524 "GET / HTTP/1.1" 500 100112
WARNING 2025-10-29 11:35:02,669 log 118344 151524 Not Found: /favicon.ico
WARNING 2025-10-29 11:35:02,670 basehttp 118344 151524 "GET /favicon.ico HTTP/1.1" 404 2844
ERROR 2025-10-29 11:35:04,402 log 118344 151524 Internal Server Error: /
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'dashboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 259, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 249, in get_redirect_url
    url = reverse(self.pattern_name, args=args, kwargs=kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'dashboard' is not a registered namespace
ERROR 2025-10-29 11:35:04,404 basehttp 118344 151524 "GET / HTTP/1.1" 500 100112
WARNING 2025-10-29 11:35:04,634 log 118344 151524 Not Found: /favicon.ico
WARNING 2025-10-29 11:35:04,635 basehttp 118344 151524 "GET /favicon.ico HTTP/1.1" 404 2844
ERROR 2025-10-29 11:35:21,091 log 118344 151524 Internal Server Error: /
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'dashboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 259, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\views\generic\base.py", line 249, in get_redirect_url
    url = reverse(self.pattern_name, args=args, kwargs=kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'dashboard' is not a registered namespace
ERROR 2025-10-29 11:35:21,094 basehttp 118344 151524 "GET / HTTP/1.1" 500 100112
WARNING 2025-10-29 11:35:21,309 log 118344 151524 Not Found: /favicon.ico
WARNING 2025-10-29 11:35:21,310 basehttp 118344 151524 "GET /favicon.ico HTTP/1.1" 404 2844
ERROR 2025-10-29 11:35:23,456 log 150776 127532 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-10-29 11:35:23,458 basehttp 150776 127532 "GET /accounts/login/?next=/dashboard/ HTTP/1.1" 500 87638
WARNING 2025-10-29 11:35:23,708 log 150776 127532 Not Found: /favicon.ico
WARNING 2025-10-29 11:35:23,709 basehttp 150776 127532 "GET /favicon.ico HTTP/1.1" 404 2997
ERROR 2025-10-29 11:35:25,134 log 150776 127532 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-10-29 11:35:25,136 basehttp 150776 127532 "GET /accounts/login/?next=/dashboard/ HTTP/1.1" 500 87638
WARNING 2025-10-29 11:35:25,327 log 150776 127532 Not Found: /favicon.ico
WARNING 2025-10-29 11:35:25,327 basehttp 150776 127532 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 11:43:14,676 basehttp 96512 11832 "GET /static/css/styles.css HTTP/1.1" 404 1969
WARNING 2025-10-29 11:43:15,626 log 96512 122872 Not Found: /favicon.ico
WARNING 2025-10-29 11:43:15,627 basehttp 96512 122872 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 11:45:16,895 basehttp 58168 147492 "GET /static/css/styles.css HTTP/1.1" 404 1969
WARNING 2025-10-29 11:45:19,062 log 58168 147396 Not Found: /favicon.ico
WARNING 2025-10-29 11:45:19,063 basehttp 58168 147396 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 11:45:27,375 log 58168 147396 Not Found: /favicon.ico
WARNING 2025-10-29 11:45:27,376 basehttp 58168 147396 "GET /favicon.ico HTTP/1.1" 404 2997
ERROR 2025-10-29 11:45:53,207 log 58168 147396 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 7, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'danhsachthongbao' not found. 'danhsachthongbao' is not a valid view function or pattern name.
ERROR 2025-10-29 11:45:53,220 basehttp 58168 147396 "GET /dashboard/ HTTP/1.1" 500 177687
WARNING 2025-10-29 11:47:18,021 log 58168 150704 Not Found: /favicon.ico
WARNING 2025-10-29 11:47:18,023 basehttp 58168 150704 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 11:53:31,320 log 135356 149184 Not Found: /favicon.ico
WARNING 2025-10-29 11:53:31,322 basehttp 135356 149184 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 11:55:07,579 log 135356 150080 Not Found: /favicon.ico
WARNING 2025-10-29 11:55:07,580 basehttp 135356 150080 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 11:55:28,211 log 135356 150080 Not Found: /favicon.ico
WARNING 2025-10-29 11:55:28,212 basehttp 135356 150080 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 12:05:42,002 log 135356 152368 Not Found: /favicon.ico
WARNING 2025-10-29 12:05:42,003 basehttp 135356 152368 "GET /favicon.ico HTTP/1.1" 404 2997
ERROR 2025-10-29 12:06:22,374 log 135356 152368 Internal Server Error: /dichvudiennuoc/baocaodoanhthu/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 128, in view_bao_cao_doanh_thu
    initial_data = get_filtered_revenue_data()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_filtered_revenue_data() missing 1 required positional argument: 'request'
ERROR 2025-10-29 12:06:22,380 basehttp 135356 152368 "GET /dichvudiennuoc/baocaodoanhthu/ HTTP/1.1" 500 78295
ERROR 2025-10-29 12:06:25,883 log 135356 152368 Internal Server Error: /dichvudiennuoc/baocaodoanhthu/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 128, in view_bao_cao_doanh_thu
    initial_data = get_filtered_revenue_data()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_filtered_revenue_data() missing 1 required positional argument: 'request'
ERROR 2025-10-29 12:06:25,887 basehttp 135356 152368 "GET /dichvudiennuoc/baocaodoanhthu/ HTTP/1.1" 500 78295
ERROR 2025-10-29 12:06:33,564 log 135356 152368 Internal Server Error: /dichvudiennuoc/baocaodoanhthu/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 128, in view_bao_cao_doanh_thu
    initial_data = get_filtered_revenue_data()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_filtered_revenue_data() missing 1 required positional argument: 'request'
ERROR 2025-10-29 12:06:33,566 basehttp 135356 152368 "GET /dichvudiennuoc/baocaodoanhthu/ HTTP/1.1" 500 78317
WARNING 2025-10-29 12:07:30,432 log 117080 71036 Not Found: /favicon.ico
WARNING 2025-10-29 12:07:30,434 basehttp 117080 71036 "GET /favicon.ico HTTP/1.1" 404 2997
ERROR 2025-10-29 13:23:57,345 forms 117080 148976 Failed to send password reset email to 1
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\forms.py", line 434, in send_mail
    email_message.send()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
ERROR 2025-10-29 13:24:35,904 forms 117080 148976 Failed to send password reset email to 1
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\forms.py", line 434, in send_mail
    email_message.send()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\thanhduong\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
WARNING 2025-10-29 15:24:15,227 log 157140 150220 Not Found: /favicon.ico
WARNING 2025-10-29 15:24:15,230 basehttp 157140 150220 "GET /favicon.ico HTTP/1.1" 404 2997
WARNING 2025-10-29 15:26:22,868 log 10128 153888 Not Found: /favicon.ico
WARNING 2025-10-29 15:26:22,870 basehttp 10128 153888 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:26:29,881 log 10128 153888 Not Found: /a
WARNING 2025-10-29 15:26:29,883 basehttp 10128 153888 "GET /a HTTP/1.1" 404 2954
WARNING 2025-10-29 15:33:30,516 log 149220 149492 Not Found: /favicon.ico
WARNING 2025-10-29 15:33:30,517 basehttp 149220 149492 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:33:58,135 log 149220 149492 Not Found: /favicon.ico
WARNING 2025-10-29 15:33:58,137 basehttp 149220 149492 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:36:26,485 log 149220 149492 Not Found: /favicon.ico
WARNING 2025-10-29 15:36:26,486 basehttp 149220 149492 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:37:59,125 log 149220 149492 Not Found: /favicon.ico
WARNING 2025-10-29 15:37:59,125 basehttp 149220 149492 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:41:04,879 log 149220 149492 Not Found: /favicon.ico
WARNING 2025-10-29 15:41:04,880 basehttp 149220 149492 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:41:09,655 log 149220 149492 Not Found: /favicon.ico
WARNING 2025-10-29 15:41:09,657 basehttp 149220 149492 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 15:41:22,441 log 149220 149492 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-29 15:41:22,443 basehttp 149220 149492 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3095
WARNING 2025-10-29 15:42:14,607 log 149220 155764 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-29 15:42:14,609 basehttp 149220 155764 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3095
WARNING 2025-10-29 15:42:20,275 log 149220 155764 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-29 15:42:20,276 basehttp 149220 155764 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3095
WARNING 2025-10-29 15:42:26,173 log 149220 155764 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-29 15:42:26,174 basehttp 149220 155764 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3095
WARNING 2025-10-29 15:42:35,740 log 149220 155764 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-29 15:42:35,742 basehttp 149220 155764 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3095
WARNING 2025-10-29 15:44:30,571 log 149220 154480 Not Found: /favicon.ico
WARNING 2025-10-29 15:44:30,572 basehttp 149220 154480 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 17:31:35,914 log 26312 151040 Not Found: /favicon.ico
WARNING 2025-10-29 17:31:35,915 basehttp 26312 151040 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-29 17:48:57,271 log 157068 151576 Forbidden (Permission denied): /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 56, in _view_wrapper
    test_pass = test_func(request.user)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 129, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2025-10-29 17:48:57,452 basehttp 157068 151576 "GET /dashboard/ HTTP/1.1" 403 135
WARNING 2025-10-29 17:50:03,716 log 125912 150516 Forbidden (Permission denied): /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 56, in _view_wrapper
    test_pass = test_func(request.user)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 129, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2025-10-29 17:50:03,884 basehttp 125912 150516 "GET /dashboard/ HTTP/1.1" 403 135
WARNING 2025-10-29 17:50:04,275 log 125912 150516 Not Found: /favicon.ico
WARNING 2025-10-29 17:50:04,275 basehttp 125912 150516 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-30 09:27:47,467 log 103400 163172 Forbidden (Permission denied): /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 56, in _view_wrapper
    test_pass = test_func(request.user)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 129, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
WARNING 2025-10-30 09:27:47,746 basehttp 103400 163172 "GET /dashboard/ HTTP/1.1" 403 135
WARNING 2025-10-30 09:30:47,336 log 161604 147624 Not Found: /favicon.ico
WARNING 2025-10-30 09:30:47,337 basehttp 161604 147624 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-30 09:33:04,692 log 151632 162900 Not Found: /favicon.ico
WARNING 2025-10-30 09:33:04,695 basehttp 151632 162900 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-30 09:33:19,631 log 151632 158836 Not Found: /favicon.ico
WARNING 2025-10-30 09:33:19,633 basehttp 151632 158836 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-30 09:34:11,664 log 143952 152992 Not Found: /favicon.ico
WARNING 2025-10-30 09:34:11,665 basehttp 143952 152992 "GET /favicon.ico HTTP/1.1" 404 2984
WARNING 2025-10-30 17:48:02,163 log 20736 22088 Not Found: /favicon.ico
WARNING 2025-10-30 17:48:02,164 basehttp 20736 22088 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-30 17:48:28,007 log 20736 22088 Internal Server Error: /dichvudiennuoc/api/danh-sach-thong-bao/
ERROR 2025-10-30 17:48:28,009 basehttp 20736 22088 "GET /dichvudiennuoc/api/danh-sach-thong-bao/?month=&year=&company=&page=1&per_page=10 HTTP/1.1" 500 430
ERROR 2025-10-30 17:48:28,279 log 20736 20456 Internal Server Error: /dichvudiennuoc/api/danh-sach-cong-ty/
ERROR 2025-10-30 17:48:28,283 basehttp 20736 20456 "GET /dichvudiennuoc/api/danh-sach-cong-ty/ HTTP/1.1" 500 179
ERROR 2025-10-30 17:49:03,744 log 20736 6460 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column HopDong.Id_HopDong does not exist
LINE 1: SELECT "HopDong"."Id_HopDong", "HopDong"."TenCongTy", "HopDo...
               ^
HINT:  Perhaps you meant to reference the column "HopDong.MaHopDong" or the column "HopDong.TenHopDong".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column HopDong.Id_HopDong does not exist
LINE 1: SELECT "HopDong"."Id_HopDong", "HopDong"."TenCongTy", "HopDo...
               ^
HINT:  Perhaps you meant to reference the column "HopDong.MaHopDong" or the column "HopDong.TenHopDong".

ERROR 2025-10-30 17:49:03,746 basehttp 20736 6460 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 136368
ERROR 2025-10-31 10:09:23,630 log 22236 34984 Internal Server Error: /dichvudiennuoc/api/danh-sach-thong-bao/
ERROR 2025-10-31 10:09:23,631 basehttp 22236 34984 "GET /dichvudiennuoc/api/danh-sach-thong-bao/?month=&year=&company=&page=1&per_page=10 HTTP/1.1" 500 301
ERROR 2025-10-31 10:09:24,031 log 22236 35416 Internal Server Error: /dichvudiennuoc/api/danh-sach-cong-ty/
ERROR 2025-10-31 10:09:24,033 basehttp 22236 35416 "GET /dichvudiennuoc/api/danh-sach-cong-ty/ HTTP/1.1" 500 222
ERROR 2025-10-31 10:09:24,044 log 22236 29208 Internal Server Error: /dichvudiennuoc/api/danh-sach-tat-ca-dich-vu/
ERROR 2025-10-31 10:09:24,046 basehttp 22236 29208 "GET /dichvudiennuoc/api/danh-sach-tat-ca-dich-vu/ HTTP/1.1" 500 222
ERROR 2025-10-31 10:09:31,986 log 22236 29208 Internal Server Error: /dichvudiennuoc/baocaodoanhthu/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "public.ThanhToan_DichVu" does not exist
LINE 1: ...ngTienTruocThue"))), 0.0) AS "total_revenue" FROM "public.Th...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 127, in view_bao_cao_doanh_thu
    initial_data = get_filtered_revenue_data()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 55, in get_filtered_revenue_data
    summary_agg_thanhtoan_qs = thanhtoan_qs.aggregate(
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 588, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "public.ThanhToan_DichVu" does not exist
LINE 1: ...ngTienTruocThue"))), 0.0) AS "total_revenue" FROM "public.Th...
                                                             ^

ERROR 2025-10-31 10:09:31,995 basehttp 22236 29208 "GET /dichvudiennuoc/baocaodoanhthu/ HTTP/1.1" 500 141873
ERROR 2025-10-31 10:10:28,776 log 22236 29208 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "public.HopDong" does not exist
LINE 1: ...Thai", "public.HopDong"."NgayBatDauTinhTien" FROM "public.Ho...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "public.HopDong" does not exist
LINE 1: ...Thai", "public.HopDong"."NgayBatDauTinhTien" FROM "public.Ho...
                                                             ^

ERROR 2025-10-31 10:10:28,779 basehttp 22236 29208 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 136551
ERROR 2025-10-31 10:11:59,826 log 19984 32700 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: syntax error at or near "".""
LINE 1: SELECT "public."HopDong"."Id_HopDong", "public."HopDong"."Te...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: syntax error at or near "".""
LINE 1: SELECT "public."HopDong"."Id_HopDong", "public."HopDong"."Te...
                               ^

ERROR 2025-10-31 10:11:59,829 basehttp 19984 32700 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 137086
WARNING 2025-10-31 10:12:00,374 log 19984 32700 Not Found: /favicon.ico
WARNING 2025-10-31 10:12:00,375 basehttp 19984 32700 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:12:14,556 log 36440 30332 Internal Server Error: /dichvudiennuoc/api/danh-sach-tat-ca-dich-vu/
ERROR 2025-10-31 10:12:14,557 basehttp 36440 30332 "GET /dichvudiennuoc/api/danh-sach-tat-ca-dich-vu/ HTTP/1.1" 500 222
ERROR 2025-10-31 10:12:14,910 log 36440 36392 Internal Server Error: /dichvudiennuoc/api/danh-sach-cong-ty/
ERROR 2025-10-31 10:12:14,911 basehttp 36440 36392 "GET /dichvudiennuoc/api/danh-sach-cong-ty/ HTTP/1.1" 500 208
ERROR 2025-10-31 10:12:14,961 log 36440 548 Internal Server Error: /dichvudiennuoc/api/danh-sach-thong-bao/
ERROR 2025-10-31 10:12:14,962 basehttp 36440 548 "GET /dichvudiennuoc/api/danh-sach-thong-bao/?month=&year=&company=&page=1&per_page=10 HTTP/1.1" 500 301
ERROR 2025-10-31 10:12:19,075 log 36440 548 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.SyntaxError: zero-length delimited identifier at or near """"
LINE 1: SELECT "public."HopDong""."Id_HopDong", "public."HopDong""."...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: zero-length delimited identifier at or near """"
LINE 1: SELECT "public."HopDong""."Id_HopDong", "public."HopDong""."...
                               ^

ERROR 2025-10-31 10:12:19,078 basehttp 36440 548 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 137673
WARNING 2025-10-31 10:12:19,577 log 36440 548 Not Found: /favicon.ico
WARNING 2025-10-31 10:12:19,578 basehttp 36440 548 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:12:44,950 log 37404 16472 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "public.HopDong" does not exist
LINE 1: ...Thai", "public.HopDong"."NgayBatDauTinhTien" FROM "public.Ho...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "public.HopDong" does not exist
LINE 1: ...Thai", "public.HopDong"."NgayBatDauTinhTien" FROM "public.Ho...
                                                             ^

ERROR 2025-10-31 10:12:44,954 basehttp 37404 16472 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 136816
WARNING 2025-10-31 10:12:45,453 log 37404 16472 Not Found: /favicon.ico
WARNING 2025-10-31 10:12:45,454 basehttp 37404 16472 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:14:08,293 log 6388 19492 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "public.hopdong" does not exist
LINE 1: ...Thai", "public.hopdong"."NgayBatDauTinhTien" FROM "public.ho...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "public.hopdong" does not exist
LINE 1: ...Thai", "public.hopdong"."NgayBatDauTinhTien" FROM "public.ho...
                                                             ^

ERROR 2025-10-31 10:14:08,298 basehttp 6388 19492 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 136816
WARNING 2025-10-31 10:14:08,789 log 6388 19492 Not Found: /favicon.ico
WARNING 2025-10-31 10:14:08,790 basehttp 6388 19492 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:14:23,151 log 3336 32464 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "public.HopDong_DichVu" does not exist
LINE 1: ...uThich", "public.HopDong_DichVu"."DonViTinh" FROM "public.Ho...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1951, in _fetch_all
    self._prefetch_related_objects()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1328, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 2397, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(
                                   ^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 2561, in prefetch_one_level
    ) = prefetcher.get_prefetch_querysets(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 800, in get_prefetch_querysets
    for rel_obj in queryset:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "public.HopDong_DichVu" does not exist
LINE 1: ...uThich", "public.HopDong_DichVu"."DonViTinh" FROM "public.Ho...
                                                             ^

ERROR 2025-10-31 10:14:23,156 basehttp 3336 32464 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 177379
WARNING 2025-10-31 10:14:23,660 log 3336 32464 Not Found: /favicon.ico
WARNING 2025-10-31 10:14:23,661 basehttp 3336 32464 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:14:33,648 log 35204 32416 Internal Server Error: /dichvudiennuoc/quanlykhachthue/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "public.DichVu" does not exist
LINE 1: ...ichVu"."ChuThich", "public.DichVu"."NgayGhi" FROM "public.Di...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 1204, in view_quan_ly_khach_thue
    for hopdong in hopdong_list:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1951, in _fetch_all
    self._prefetch_related_objects()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1328, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 2397, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(
                                   ^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 2598, in prefetch_one_level
    all_related_objects = list(rel_qs)
                          ^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "public.DichVu" does not exist
LINE 1: ...ichVu"."ChuThich", "public.DichVu"."NgayGhi" FROM "public.Di...
                                                             ^

ERROR 2025-10-31 10:14:33,654 basehttp 35204 32416 "GET /dichvudiennuoc/quanlykhachthue/ HTTP/1.1" 500 165042
WARNING 2025-10-31 10:14:34,104 log 35204 32416 Not Found: /favicon.ico
WARNING 2025-10-31 10:14:34,105 basehttp 35204 32416 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:35:21,794 log 33728 36244 Not Found: /favicon.ico
WARNING 2025-10-31 10:35:21,796 basehttp 33728 36244 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:37:05,229 log 31504 14048 Not Found: /favicon.ico
WARNING 2025-10-31 10:37:05,229 basehttp 31504 14048 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:37:14,978 log 31504 14048 Not Found: /favicon.ico
WARNING 2025-10-31 10:37:14,980 basehttp 31504 14048 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:38:09,428 log 31504 14048 Not Found: /favicon.ico
WARNING 2025-10-31 10:38:09,429 basehttp 31504 14048 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:39:34,984 log 38060 34952 Not Found: /favicon.ico
WARNING 2025-10-31 10:39:34,984 basehttp 38060 34952 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:39:56,690 log 38060 34952 Not Found: /favicon.ico
WARNING 2025-10-31 10:39:56,692 basehttp 38060 34952 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:42:06,938 log 30764 36156 Internal Server Error: /hrm/core/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "hrm.HopDong" does not exist
LINE 1: ...pDong"."LoaiHopDong", "hrm.HopDong"."GhiChu" FROM "hrm.HopDo...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\hrm_manager\__core__\views.py", line 9, in index
    print(models_Hopdong)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 360, in __repr__
    data = list(self[: REPR_OUTPUT_SIZE + 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "hrm.HopDong" does not exist
LINE 1: ...pDong"."LoaiHopDong", "hrm.HopDong"."GhiChu" FROM "hrm.HopDo...
                                                             ^

ERROR 2025-10-31 10:42:06,946 basehttp 30764 36156 "GET /hrm/core/ HTTP/1.1" 500 137822
WARNING 2025-10-31 10:42:59,070 log 37356 19792 Not Found: /favicon.ico
WARNING 2025-10-31 10:42:59,072 basehttp 37356 19792 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:43:17,034 log 37356 19792 Not Found: /favicon.ico
WARNING 2025-10-31 10:43:17,036 basehttp 37356 19792 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:50:42,397 log 35240 20608 Internal Server Error: /dichvudiennuoc/danhsachthongbao/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'quan_ly_luong'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 301, in view_danh_sach_thong_bao
    return render(request, "dich_vu_dien_nuoc/danh_sach_thong_bao.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'quan_ly_luong' is not a registered namespace
ERROR 2025-10-31 10:50:42,402 basehttp 35240 20608 "GET /dichvudiennuoc/danhsachthongbao/ HTTP/1.1" 500 195114
WARNING 2025-10-31 10:50:42,938 log 35240 20608 Not Found: /favicon.ico
WARNING 2025-10-31 10:50:42,939 basehttp 35240 20608 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:52:13,522 log 36520 35712 Internal Server Error: /dichvudiennuoc/danhsachthongbao/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dich_vu_dien_nuoc\views.py", line 301, in view_danh_sach_thong_bao
    return render(request, "dich_vu_dien_nuoc/danh_sach_thong_bao.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'quanlynhansu' not found. 'quanlynhansu' is not a valid view function or pattern name.
ERROR 2025-10-31 10:52:13,529 basehttp 36520 35712 "GET /dichvudiennuoc/danhsachthongbao/ HTTP/1.1" 500 193383
WARNING 2025-10-31 10:52:14,044 log 36520 35712 Not Found: /favicon.ico
WARNING 2025-10-31 10:52:14,044 basehttp 36520 35712 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 10:52:18,021 log 36520 35712 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 8, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'quanlynhansu' not found. 'quanlynhansu' is not a valid view function or pattern name.
ERROR 2025-10-31 10:52:18,024 basehttp 36520 35712 "GET /dashboard/ HTTP/1.1" 500 185031
ERROR 2025-10-31 10:53:31,352 log 30040 5464 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 8, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
ERROR 2025-10-31 10:53:31,357 basehttp 30040 5464 "GET /dashboard/ HTTP/1.1" 500 185052
WARNING 2025-10-31 10:53:31,877 log 30040 5464 Not Found: /favicon.ico
WARNING 2025-10-31 10:53:31,878 basehttp 30040 5464 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 10:54:18,574 log 30040 5464 Not Found: /favicon.ico
WARNING 2025-10-31 10:54:18,577 basehttp 30040 5464 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 11:00:38,876 log 30040 30648 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: partials/_submenu.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 8, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: partials/_submenu.html
ERROR 2025-10-31 11:00:38,881 basehttp 30040 30648 "GET /dashboard/ HTTP/1.1" 500 183016
WARNING 2025-10-31 11:00:39,516 log 30040 30648 Not Found: /favicon.ico
WARNING 2025-10-31 11:00:39,517 basehttp 30040 30648 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 11:01:08,051 log 12724 10664 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: partials/_submenu.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 8, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: partials/_submenu.html
ERROR 2025-10-31 11:01:08,054 basehttp 12724 10664 "GET /dashboard/ HTTP/1.1" 500 183016
WARNING 2025-10-31 11:01:08,551 log 12724 10664 Not Found: /favicon.ico
WARNING 2025-10-31 11:01:08,552 basehttp 12724 10664 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 11:01:25,643 log 12724 10664 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 8, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 590, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 35: 'if'. Looking for one of: elif, else, endif.
ERROR 2025-10-31 11:01:25,645 basehttp 12724 10664 "GET /dashboard/ HTTP/1.1" 500 201954
WARNING 2025-10-31 11:01:26,146 log 12724 10664 Not Found: /favicon.ico
WARNING 2025-10-31 11:01:26,148 basehttp 12724 10664 "GET /favicon.ico HTTP/1.1" 404 3131
ERROR 2025-10-31 11:01:33,113 log 12724 10664 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\apps\dashboard\views.py", line 8, in index
    return render(request, "dashboard/index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "E:\Django\TanPhong_Manager_Project\.venv\Lib\site-packages\django\template\base.py", line 590, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 35: 'if'. Looking for one of: elif, else, endif.
ERROR 2025-10-31 11:01:33,116 basehttp 12724 10664 "GET /dashboard/ HTTP/1.1" 500 201954
WARNING 2025-10-31 11:01:33,573 log 12724 10664 Not Found: /favicon.ico
WARNING 2025-10-31 11:01:33,574 basehttp 12724 10664 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 11:04:23,520 log 12724 10664 Not Found: /favicon.ico
WARNING 2025-10-31 11:04:23,522 basehttp 12724 10664 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 11:46:30,849 log 12724 37236 Not Found: /favicon.ico
WARNING 2025-10-31 11:46:30,850 basehttp 12724 37236 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 11:48:23,407 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:23,409 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:30,925 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:30,927 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:34,967 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:34,969 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:37,947 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:37,948 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:42,584 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:42,585 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:50,509 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:50,510 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:53,527 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:53,528 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:48:59,728 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:48:59,730 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:49:03,479 log 12724 37236 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:49:03,480 basehttp 12724 37236 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:49:23,272 log 12724 35120 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:49:23,273 basehttp 12724 35120 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:49:27,414 log 12724 31936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:49:27,416 basehttp 12724 31936 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 11:49:38,865 log 12724 31936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 11:49:38,867 basehttp 12724 31936 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 14:57:03,475 log 12724 37396 Not Found: /favicon.ico
WARNING 2025-10-31 14:57:03,477 basehttp 12724 37396 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 15:02:23,932 log 12724 28936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:02:23,933 basehttp 12724 28936 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:02:36,669 log 12724 28936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:02:36,670 basehttp 12724 28936 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:02:40,367 log 12724 28936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:02:40,368 basehttp 12724 28936 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:06:12,973 log 12724 37044 Not Found: /favicon.ico
WARNING 2025-10-31 15:06:12,977 basehttp 12724 37044 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 15:07:08,587 log 12724 35680 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:07:08,588 basehttp 12724 35680 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:07:14,857 log 12724 35680 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:07:14,858 basehttp 12724 35680 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:07:32,724 log 12724 37044 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:07:32,725 basehttp 12724 37044 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:07:36,670 log 12724 37044 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:07:36,671 basehttp 12724 37044 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:07:51,460 log 12724 37044 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:07:51,461 basehttp 12724 37044 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:07:55,882 log 12724 37044 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:07:55,883 basehttp 12724 37044 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:20:48,477 log 12724 21088 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:20:48,478 basehttp 12724 21088 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:24:02,483 log 12724 21088 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:24:02,484 basehttp 12724 21088 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:24:31,992 log 12724 21088 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:24:31,994 basehttp 12724 21088 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:24:36,905 log 12724 21088 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:24:36,907 basehttp 12724 21088 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:24:37,779 log 12724 21088 Not Found: /favicon.ico
WARNING 2025-10-31 15:24:37,781 basehttp 12724 21088 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 15:27:45,904 log 12724 21088 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 15:27:45,904 basehttp 12724 21088 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 15:32:47,813 log 12724 37592 Not Found: /favicon.ico
WARNING 2025-10-31 15:32:47,814 basehttp 12724 37592 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 15:33:26,450 log 12724 8228 Not Found: /favicon.ico
WARNING 2025-10-31 15:33:26,452 basehttp 12724 8228 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 16:49:40,450 log 32996 36704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 16:49:40,454 basehttp 32996 36704 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 16:50:03,208 log 32996 36704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 16:50:03,209 basehttp 32996 36704 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 16:50:18,019 log 32996 36704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 16:50:18,020 basehttp 32996 36704 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:24:23,678 log 32996 36768 Not Found: /favicon.ico
WARNING 2025-10-31 17:24:23,679 basehttp 32996 36768 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 17:39:39,182 log 32996 21088 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:39:39,184 basehttp 32996 21088 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:11,722 log 32996 34532 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:11,723 basehttp 32996 34532 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:15,101 log 32996 34532 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:15,103 basehttp 32996 34532 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:20,383 log 32996 32612 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:20,384 basehttp 32996 32612 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:21,118 log 32996 32612 Not Found: /favicon.ico
WARNING 2025-10-31 17:40:21,119 basehttp 32996 32612 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-10-31 17:40:30,343 log 32996 32612 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:30,344 basehttp 32996 32612 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:33,231 log 32996 32612 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:33,233 basehttp 32996 32612 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:36,176 log 32996 37468 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:36,177 basehttp 32996 37468 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:38,948 log 32996 37468 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:38,949 basehttp 32996 37468 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:40:59,988 log 32996 35992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:40:59,989 basehttp 32996 35992 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:41:02,950 log 32996 35992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:41:02,952 basehttp 32996 35992 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 17:41:06,317 log 32996 35992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-31 17:41:06,318 basehttp 32996 35992 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
WARNING 2025-10-31 20:04:02,963 log 32996 39984 Not Found: /favicon.ico
WARNING 2025-10-31 20:04:02,966 basehttp 32996 39984 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-11-01 09:20:59,631 log 32996 47148 Not Found: /favicon.ico
WARNING 2025-11-01 09:20:59,632 basehttp 32996 47148 "GET /favicon.ico HTTP/1.1" 404 3131
WARNING 2025-11-01 09:25:56,067 log 32996 26724 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-11-01 09:25:56,068 basehttp 32996 26724 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3242
